[package]
name = "tilemage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ea_suite_lib = {path = "../../lib"}
anyhow = "1.0.81"
clap = { version = "4.5.34", features = ["derive"] }
image = "0.25.6"
atty = "0.2"
